#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// This script moves German content to root after static export
const outDir = path.join(process.cwd(), 'out');
const deDir = path.join(outDir, 'de');

console.log('📦 Reorganizing static files - German as root...');

if (fs.existsSync(deDir)) {
  // Backup existing root index if exists
  const rootIndex = path.join(outDir, 'index.html');
  if (fs.existsSync(rootIndex)) {
    fs.renameSync(rootIndex, path.join(outDir, 'index.backup.html'));
  }
  
  // Since we now have a native root page, we don't need to copy German anymore
  // The root page is already generated by Next.js
  console.log('✅ Root page already generated by Next.js');
  
  // Keep the German version in /de folder as well for direct access
  console.log('✅ German version also available at /de');
}

console.log('✅ Static reorganization complete!');